apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-motion-test
  namespace: logi-core
  labels:
    app: flow-motion
    component: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flow-motion
      component: test
  template:
    metadata:
      labels:
        app: flow-motion
        component: test
    spec:
      containers:
      - name: flow-motion
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: flow-motion-test-service
  namespace: logi-core
spec:
  selector:
    app: flow-motion
    component: test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
