apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
  labels:
    app: api-gateway
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values in production
  # echo -n 'your-super-secret-jwt-key-here' | base64
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1oZXJl
  # echo -n 'your-refresh-secret-jwt-key-here' | base64
  JWT_REFRESH_SECRET: eW91ci1yZWZyZXNoLXNlY3JldC1qd3Qta2V5LWhlcmU=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  labels:
    app: api-gateway
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  METRICS_ENABLED: "true"